# change source and team
source: https://<GIT_SERVER>/<USER_NAME>/mlops-gitops.git
team: <USER_NAME>
release: mlops

applications:
  # Tooling to support CI/CD
  - name: toolings
    enabled: true
    source_path: "."
    helm_values:
      - toolings/values.yaml

  # Test App of Apps for Models
  - name: test-app-of-models
    enabled: false
    source_path: "."
    helm_values:
      - model-deployments/test/values.yaml

  # Production App of Apps for Models
  - name: prod-app-of-models
    enabled: false
    source_path: "."
    helm_values:
      - model-deployments/prod/values.yaml