applications:
  # Bootstrap Project
  - name: bootstrap
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: bootstrap-project
    source_ref: "1.0.1"
    values:
      serviceaccounts: ""
      # student is the GROUP NAME in IDM
      bindings: &binds
        - name: USER_NAME
          kind: User
          role: admin
      namespaces:
        - name: USER_NAME-mlops
          bindings: *binds
          operatorgroup: true
        - name: USER_NAME-test
          bindings: *binds
          operatorgroup: true
        - name: USER_NAME-stage
          bindings: *binds
          operatorgroup: true

  # Minio
  - name: minio
    enabled: true
    source: https://rhoai-mlops.github.io/mlops-helmcharts/
    chart_name: minio
    source_ref: "0.0.7"
    values:
      buckets:
        - name: pipeline
        - name: models


  # KubeFlow Model Registry


  # Data Science Pipeline Application


  # CT Pipeline

